export const RUNTIME_ERROR_CODE = {
  NOT_STARTED: 'RUNTIME_NOT_STARTED',
  TIMEOUT: 'RUNTIME_TIMEOUT',
  CANCELLED: 'RUNTIME_CANCELLED',
  STOPPED: 'RUNTIME_STOPPED',
  CRASHED: 'RUNTIME_CRASHED',
  HANDSHAKE_FAILED: 'RUNTIME_HANDSHAKE_FAILED'
} as const
