export const RUNTIME_ERROR_CODE = {
  NOT_STARTED: 'RUNTIME_NOT_STARTED',
  TIMEOUT: 'RUNTIME_TIMEOUT',
  CANCELLED: 'RUNTIME_CANCELLED',
  STOPPED: 'RUNTIME_STOPPED',
  CRASHED: 'RUNTIME_CRASHED',
  HANDSHAKE_FAILED: 'RUNTIME_HANDSHAKE_FAILED',
  RESPONSE_INVALID: 'RUNTIME_RESPONSE_INVALID',
  PLAN_INVALID: 'RUNTIME_PLAN_INVALID',
  PLAN_NOT_BUILDABLE: 'PLAN_NOT_BUILDABLE',
  DB_FAILED: 'RUNTIME_DB_FAILED',
  ORPHANED: 'RUNTIME_ORPHANED'
} as const
