export const ERROR_CODE = {
  PROTOCOL_INVALID_JSON: "PROTOCOL_INVALID_JSON",
  PROTOCOL_INVALID_REQUEST: "PROTOCOL_INVALID_REQUEST",
  METHOD_NOT_FOUND: "METHOD_NOT_FOUND",
  NOT_IMPLEMENTED: "NOT_IMPLEMENTED",
  FILESYSTEM_ROOT_UNAVAILABLE: "FILESYSTEM_ROOT_UNAVAILABLE",
  HOST_HANDLER_FAILED: "HOST_HANDLER_FAILED",
  HOST_TIMEOUT: "HOST_TIMEOUT",
  INVALID_ARGUMENT: "INVALID_ARGUMENT",
  CAPABILITY_OUT_OF_SCOPE: "CAPABILITY_OUT_OF_SCOPE",
  CAPABILITY_NOT_REGISTERED: "CAPABILITY_NOT_REGISTERED",
  PATH_OUT_OF_ROOT: "PATH_OUT_OF_ROOT",
} as const;