export const ERROR_CODE = {
  PROTOCOL_INVALID_JSON: "PROTOCOL_INVALID_JSON",
  PROTOCOL_INVALID_REQUEST: "PROTOCOL_INVALID_REQUEST",
  METHOD_NOT_FOUND: "METHOD_NOT_FOUND",
  NOT_IMPLEMENTED: "NOT_IMPLEMENTED",
  FILESYSTEM_ROOT_UNAVAILABLE: "FILESYSTEM_ROOT_UNAVAILABLE",
} as const;
